from pinyin_util import pinyin_numbers_to_marks

TESTS = [
    ("", ""),
    ("xian1", "xiān"),
    ("xi1", "xī"),
    ("xi", "xi"),
    ("la4", "là"),
    ("la", "la"),
    ("la5", "la"),
    ("xi1an1", "xī'ān"),
    ("wan3an1", "wǎn'ān"),
    ("tian1e2", "tiān'é"),
    ("xian4zai4", "xiànzài"),
    ("liao3", "liǎo"),
    ("an1ba", "ānba"),
    ("an1ba1", "ānbā"),
    ("zhe4ge", "zhège"),
    ("zhe4ge5", "zhège"),
    ("lv3cheng2", "lǚchéng"),
    ("lvcheng", "lücheng"),
    ("lv3", "lǚ"),
    ("lv", "lü"),
    ("kao4lv", "kàolü"),
    ("kaolv3", "kaolǚ"),
    ("not pinyin with numbers 1", "not pinyin with numbers 1"),
    ("xiànzai4", "xiànzài"),
    ("xianzai4", "xianzài"),
    ("<b>xian1</b>", "<b>xiān</b>"),
    ('<span style="color:red">xian1</span>', '<span style="color:red">xiān</span>'),
    ("{{Field}} xian1", "{{Field}} xiān"),
    ("{{#Field}}xian1{{/Field}}", "{{#Field}}xian1{{/Field}}"),
    ("{{^Field}}xian1{{/Field}}", "{{^Field}}xian1{{/Field}}"),
    ("{{c1::xian1::hint}}", "{{c1::xian1::hint}}"),
    ("[sound:xian1.mp3] xian1", "[sound:xian1.mp3] xiān"),
    (r"\( xian1 \) xian1", r"\( xian1 \) xiān"),
    (r"\[ xian1 \] xian1", r"\[ xian1 \] xiān"),
    ("[$] xian1 [/$] xian1", "[$] xian1 [/$] xiān"),
    ("&nbsp;xian1", "&nbsp;xiān"),
    ("<!-- xian1 --> xian1", "<!-- xian1 --> xiān"),
    ("<script>xian1</script> xian1", "<script>xian1</script> xiān"),
    ("<style>xian1</style> xian1", "<style>xian1</style> xiān"),
    ("https://example.com/xian1 xian1", "https://example.com/xian1 xiān"),
    (
        '<a href="https://example.com/xian1">xian1</a>',
        '<a href="https://example.com/xian1">xiān</a>',
    ),
    ("xian888888883", "xian888888883"),
    ("xian123456", "xian123456"),
    ("xian 1", "xian 1"),
    ("xian!1", "xian!1"),
    ("xian-1", "xian-1"),
]

for input, output in TESTS:
    result = pinyin_numbers_to_marks(input)
    assert result == output, f"test failed for {input}: got {result} expected {output}"
print("All checks passed")
